### ISSUE TITLE
Blender Source Model Tools [Red_Eye's Source Model Utils] addon installation

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/io_mesh_SourceMDL#1]
Hi, what is the minimum Blender version?
Does this addon overwrite the BleST (**Blender Source Tools**) addon?

**Install Add-on from File...** 
- io_mesh_SourceMDL-rewrite (Didn't work)
(https://github.com/REDxEYE/io_mesh_SourceMDL/archive/rewrite.zip)
- io_mesh_SourceMDL_wF5SLAj.zip (Didn't work)
(https://smutba.se/project/245/)

Both gave me this error message:
**'File already installed to [addon directory]'**

In the Add-ons menu, I only see the BLEST addon.

**-EDIT-** It installed correctly once I ticked **'Overwrite'**.
https://i.imgur.com/jorQE4i.png
Is it overwriting another addon?

**Comment by REDxEYE** [comment]
@Gnates No it doesn't overwrite anything. Looks like you just had installed old version
