### ISSUE TITLE
AttributeError: 'bpy_prop_collection' object has no attribute 'link'

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/io_mesh_SourceMDL#11]
Blender 2.80 Beta (Date: 2019-02-02 Hash: 4ef09cf937f2)
io_mesh_SourceMDL: v2.1

SFM Model (NSFW): 
- https://sfmlab.com/item/2711/ (MDL v49 according to Crowbar)
This is the same model from the demo I made awhile ago: 
- https://gfycat.com/GlumOpenAlaskajingle

> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_SourceMDL-blender280\__init__.py", line 40, in execute
>     join_bones=self.normal_bones, join_clamped=self.join_clamped)
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_SourceMDL-blender280\io_Mdl.py", line 98, in __init__
>     self.create_attachments()
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_SourceMDL-blender280\io_Mdl.py", line 505, in create_attachments
>     bpy.context.scene.objects.link(empty)
> AttributeError: 'bpy_prop_collection' object has no attribute 'link'
> 
> location: <unknown location>:-1

I don't know if I'm copy/pasting this correctly.

**Comment by REDxEYE** [comment]
Blender changed api probably or i forgot to change this line of code

**Comment by Ganonmaster** [comment]
https://github.com/REDxEYE/io_mesh_SourceMDL/pull/12/files#diff-b401d5c4bc5a4d9a2a1d2fe496d1549f

**Comment by Gnates** [comment]
Thank you. The recent fix imports the model correctly.
