### ISSUE TITLE
Model is invisible

### ISSUE THREAD

**Issue by narbartor** [REDxEYE/io_mesh_SourceMDL#14]
When I import a model in, I get some kind of error and no actual mesh shows up, just a skeleton
![image](https://user-images.githubusercontent.com/33747159/63411318-e0745600-c427-11e9-840d-d10364eb4ce8.png)
![image](https://user-images.githubusercontent.com/33747159/63411334-e833fa80-c427-11e9-82b0-7961cf41e2be.png)

**Comment by Original-Blank** [comment]
same

**Comment by Pepmeistersi** [comment]
Have the same problem

**Comment by REDxEYE** [comment]
Don't use this addon on 2.80, use SourceIO instead
