### ISSUE TITLE
Texture Problem

### ISSUE THREAD

**Issue by CJGeterix** [REDxEYE/io_mesh_SourceMDL#2]
The model will import but the materials do not. This add-on will make my workflow much easier if I can get it working. If someone can help me I would greatly appreciate it.

**Comment by Gnates** [comment]
Any luck with his other addon? https://github.com/REDxEYE/io_texture_VTF
I haven't tried it yet.

**Comment by CJGeterix** [comment]
Nope. Still no luck. Thanks for responding though. Does it work for you or do you have the same problem?

**Comment by Gnates** [comment]
Hopefully later this week I can give the VTF addon a try. 
So far I have no issues adding textures manually.

I used to have this strange problem with shapekeys and DazV4 models decompiled with Crowbar: https://gfycat.com/AlarmedTestyKinglet
The problem appears to be gone when using the addon: https://gfycat.com/ContentSomeAmericanbittern

**Comment by Gnates** [comment]
Here is a demonstration of both the Import **MDL** and **VTF** addon:
- https://gfycat.com/GlumOpenAlaskajingle
- https://gfycat.com/ContentSomeAmericanbittern

**Comment by REDxEYE** [comment]
@CJGeterix 
> The model will import but the materials do not. This add-on will make my workflow much easier if I can get it working. If someone can help me I would greatly appreciate it.

Auto material\texture import isn't yet implemented
There are checkboxes for that, but they are only placeholders

 @Gnates  Thanks for helping!
