### ISSUE TITLE
Materials not aligning correctly

### ISSUE THREAD

**Issue by Souyu** [REDxEYE/io_mesh_SourceMDL#3]
After importing the model, the materials sometimes wouldn't be connected to the right mesh. Like the material would say leg, but changes the arm instead.

**Comment by Gnates** [comment]
Make sure to provide a download link to the model.
Screenshots or video/gif can also help.

**Comment by Souyu** [comment]
Here's the link to the model:
https://sfmlab.com/item/3137/
And heres a gif:
https://imgur.com/a/VELItmj

**Comment by REDxEYE** [comment]
This is caused by faulty algorithm that i tried to implement, it supposed to remove unused materials and re-map used, but sometimes it fails for no reason

**Comment by Gnates** [comment]
Is this a limitation or challenge in the Blender 2.79 api?

**Comment by REDxEYE** [comment]
problem on my side, not blender
