### ISSUE TITLE
Source to Blender Skeleton Script

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/io_mesh_SourceMDL#6]
Is it possible to incorporate this script in a future update?
- https://smutba.se/project/59/ (**SFM to Blender skeleton script** by RumblingRose)
- "Ever want to port a SFM model into Blender but the imported skeleton is in unconnected bones which makes posing a complete pain? Here's the solution!"
- "Currently supports the major SFM bone name conventions..."

It would be convenient if there was a menu interface to apply the changes.

**Comment by REDxEYE** [comment]
There is already such thing
[![Image from Gyazo](https://i.gyazo.com/a4cf761a8670bfcc6acc4bc6bf18cbab.png)](https://gyazo.com/a4cf761a8670bfcc6acc4bc6bf18cbab)

**Comment by Gnates** [comment]
My mistake. Thank you for pointing it out. 
It works well too.
What does the "Join clamped meshes?" option do?

**Comment by REDxEYE** [comment]
When mesh is to hi-poly source splits it into N smaller models named "clamped-N", this option tries to join them back
