### ISSUE TITLE
Breaks Sculpt Mode?

### ISSUE THREAD

**Issue by PureRandomness** [REDxEYE/io_mesh_SourceMDL#7]
I can't see what I'm doing in Sculpt Mode when I import with this add-on. It works, but it only shows the results when I switch to Edit Mode and back. Basically editing the model blindfolded. Some Source models work in Sculpt Mode when I import with this add-on, others don't.

**Comment by REDxEYE** [comment]
Drag shapekey slider to 1.0, on 0.0 sculpting does not work
